### ISSUE TITLE
compatibility with latest Turing versions

### ISSUE THREAD

**Issue by thorek1** [marius311/MuseInference.jl#12]
Hi,

is there any chance of making MuseInference.jl compatible with the latest Turing version (currently 0.28)?

A lot happened since Turing 0.21.10 and it would greatly benefit my workflow to use later Turing versions.

Thanks

**Comment by marius311** [comment]
Looking into it. Shouldn't be too hard in theory (famous last words).

**Comment by marius311** [comment]
Can you try with https://github.com/marius311/MuseInference.jl/pull/15 and let me know if you run into any issues?

**Comment by thorek1** [comment]
works fine with 1 thread and latest Turing, not with >1 threads

**Comment by marius311** [comment]
Ok, latest Turing, including ForwardDiff w/ threads, is fixed on latest release (0.2.4). Zygote w/ threads doesn't work, but there's an informative error thrown now at least, that seems to be a bonafide issue on the DynamicPPL side.

**Comment by itsdfish** [comment]
Thank you for the package. I wanted to chime in and note that this does not work with the current release of Turing 0.33.0. Perhaps adding CompatHelper to gitactions would be a good idea.
